# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  apt: true
  directories:
  - $HOME/.opam
  - $TRAVIS_BUILD_DIR/lib/CompCert
  - $TRAVIS_BUILD_DIR/lib/paco

before_cache:
  - rm -rf ~/.opam/log/

# Ensure necessary system libraries are present
addons:
  apt:
    sources:
      - avsm
    packages:
      - libgmp-dev
      - opam

before_install:
- sudo apt-get update -qq
- opam init -n -y
- opam repo add coq-released http://coq.inria.fr/opam/released -y
- opam update -y
- opam install coq opam install -y
- opam upgrade -y

install:
- cd lib/CompCert && git pull origin master
- cd lib/Compcert && ./configure x86_64-linux && make
- make -C lib/paco/src


script:
# Build the package, its tests, and its docs and run the tests
- cd src && make
- cd src && ./vellvm --test
